---
- file: path={{docker_files}} state=directory
- copy: src={{server_conf}} dest={{docker_files}}
- docker_service:
    project_name: dhcpd
    definition:
      version: "3.3"
      services:
        isc:
          image: sirferdek/isc-dhcp-server
          volumes:
           - "{{dhcp_conf}}:/etc/dhcp/dhcpd.conf"
          networks:
            macvlan:
              ipv4_address: "{{dhcp_address}}"
      networks:
        macvlan:        
          attachable: true
          driver: macvlan
          driver_opts:
            parent: "{{intranet_iface}}"
          ipam:
            config:
            - subnet: "{{intranet_mask}}"
    state: present