---
---
- name: "AWS - Install docker"
  hosts: aws-docker-vms
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes


    - name: Ensure the EPEL yum packages is installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - epel-release


    - name: Enable EPEL Repository
      yum:
        name: epel-release
        state: latest

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - strongswan
        - xl2tpd

    - name: Delete default config files
      file: src={{item}} state=absent
      loop:
        - /etc/strongswan/ipsec.conf
        - /etc/strongswan/ipsec.secrets

    - name: Copy IPSec new config files
      copy: src={{item.src}} dest={{item.dest}} mode={{item.mode}}
      loop:
        - { src: "{{role_path}}/files/ipsec.conf", dest: "/etc/ipsec.conf", mode: 0644 }
        - { src: "{{role_path}}/files/ipsec.secrets", dest: "/etc/ipsec.secrets", mode: 0600 }
        - { src: "{{role_path}}/files/xl2tpd.conf", dest: "/etc/xl2tpd/xl2tpd.conf", mode: 0644 }
        - { src: "{{role_path}}/files/options.l2tpd.client", dest: "/etc/ppp/options.l2tpd.client", mode: 0600 }
        - { src: "{{role_path}}/files/l2tp@.service", dest: "/etc/systemd/system/l2tp@.service", mode: 0644 }

    - name: Create links
      file: src={{item.src}} dest={{item.dest}} state=link
      loop:
        - { src: "/etc/ipsec.conf", dest: "/etc/strongswan/ipsec.conf" }
        - { src: "/etc/ipsec.secrets", dest: "/etc/strongswan/ipsec.secrets"  }

    - name: Create the folders and files
      file: dest={{item.dest}} state={{item.state}}
      loop:
        - { dest: "/var/run/xl2tpd", state: directory }
        - { dest: "/var/run/xl2tpd/l2tp-control", state: touch }

    - name: Replace placeholder to the variables values
      lineinfile: path={{item.path}} line={{item.line}} regexp={{item.regexp}}
      loop:
        - {{ path: "/etc/ipsec.conf", line: "  right={{VPN_SERVER_IP}}", regexp: "  right=VPN_SERVER_IP" }}
        - {{ path: "/etc/ipsec.secrets", line: ": PSK \"{{VPN_IPSEC_PSK}}\"", regexp: ": PSK \"VPN_IPSEC_PSK\"" }}
        - {{ path: "/etc/xl2tpd/xl2tpd.conf", line: "lns = {{VPN_SERVER_IP}}", regexp: "lns = VPN_SERVER_IP" }}
        - {{ path: "/etc/ppp/options.l2tpd.client", line: "name {{VPN_USER}}", regexp: "name VPN_USER" }}
        - {{ path: "/etc/ppp/options.l2tpd.client", line: "password {{VPN_PASSWORD}}", regexp: "password VPN_PASSWORD" }}

    - name: Restart services
      systemd: name={{item.name}} {{item.state}} daemon_reload=yes enabled=true
      loop:
        - { name: "strongswan", state: "restarted" }
        - { name: "xl2tpd", state: "restarted" }
        - { name: "l2tp@myvpn", state: "started" }