---
- yum:
    name: '*'
    state: latest
    update_only: yes

- yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - amazon-linux-extras

- shell: sudo amazon-linux-extras install epel -y

- shell: sudo yum-config-manager --enable epel
  
- yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - strongswan
    - xl2tpd

- copy: src={{item.src}} dest={{item.dest}} mode={{item.mode}}
  loop:
    - { src: "{{role_path}}/files/ipsec.conf", dest: "/etc/ipsec.conf", mode: "0644" }
    - { src: "{{role_path}}/files/ipsec.secrets", dest: "/etc/ipsec.secrets", mode: "0600" }
    - { src: "{{role_path}}/files/xl2tpd.conf", dest: "/etc/xl2tpd/xl2tpd.conf", mode: "0644" }
    - { src: "{{role_path}}/files/options.l2tpd.client", dest: "/etc/ppp/options.l2tpd.client", mode: "0600" }
    - { src: "{{role_path}}/files/l2tp@.service", dest: "/etc/systemd/system/l2tp@.service", mode: "0644" }

- lineinfile: path={{item.path}} line={{item.line}} regexp={{item.regexp}}
  loop:
    - { path: "/etc/ipsec.conf", line: "  right={{VPN_SERVER_IP}}", regexp: "  right=VPN_SERVER_IP" }
    - { path: "/etc/ipsec.secrets", line: ": PSK \"{{VPN_IPSEC_PSK}}\"", regexp: ": PSK \"VPN_IPSEC_PSK\"" }
    - { path: "/etc/xl2tpd/xl2tpd.conf", line: "lns = {{VPN_SERVER_IP}}", regexp: "lns = VPN_SERVER_IP" }
    - { path: "/etc/ppp/options.l2tpd.client", line: "name {{VPN_USER}}", regexp: "name VPN_USER" }
    - { path: "/etc/ppp/options.l2tpd.client", line: "password {{VPN_PASSWORD}}", regexp: "password VPN_PASSWORD" }    

- file: path={{item}} state=absent
  loop:
    - /etc/strongswan/ipsec.conf
    - /etc/strongswan/ipsec.secrets

- file: src={{item.src}} dest={{item.dest}} state=link
  loop:
    - { src: "/etc/ipsec.conf", dest: "/etc/strongswan/ipsec.conf" }
    - { src: "/etc/ipsec.secrets", dest: "/etc/strongswan/ipsec.secrets"  }

- file: dest={{item.dest}} state={{item.state}}
  loop:
    - { dest: "/var/run/xl2tpd", state: directory }
    - { dest: "/var/run/xl2tpd/l2tp-control", state: touch }

- shell: systemctl daemon-reload
- shell: systemctl restart strongswan
- shell: systemctl restart xl2tpd  
- shell: systemctl enable --now l2tp@myvpn 
  