---
- yum: name=NetworkManager state=present
- systemd: name=NetworkManager state=started enable=yes
- sysctl: name="net.ipv4.ip_forward" value=1 state=present sysctl_set=yes reload=yes
- iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{internet_iface}}"
    jump: MASQUERADE
- iptables:
    chain: FORWARD
    in_interface: "{{internet_iface}}"
    out_interface: "{{intranet_iface}}"
    ctstate:
      - RELATED
      - ESTABLISHED
    jump: ACCEPT
- iptables:
    chain: FORWARD
    in_interface: "{{intranet_iface}}"
    out_interface: "{{internet_iface}}"
    jump: ACCEPT
- shell: ip route add "{{remote_peer_prefix}}/{{remote_peer_netmask}}" via "{{remote_peer_ip}}"