---
- sysctl: name="net.ipv4.ip_forward" value=1 state=present sysctl_set=yes reload=yes
- iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{internet_iface}}"
    jump: MASQUERADE
- iptables:
    chain: FORWARD
    in_interface: "{{internet_iface}}"
    out_interface: "{{intranet_iface}}"
    ctstate:
      - RELATED
      - ESTABLISHED
    jump: ACCEPT
- iptables:
    chain: FORWARD
    in_interface: "{{intranet_iface}}"
    out_interface: "{{internet_iface}}"
    jump: ACCEPT
- net_static_route:
    prefix: "{{remote_peer_prefix}}"
    mask: "{{remote_peer_netmask}}"
    next_hop: "{{remote_peer_ip}}"