---
- host: localhost
  become: yes
  vars:
    - internet_iface: "eth0"
    - intranet_iface: "ppp0"
    - intranet_mask: "172.31.32.0/20"
    - controller_address: "172.31.33.1"
    - controllerdb_address: "172.31.33.3"
    - dhcp_address: "172.31.33.2"
    - dhcp_conf: "{{role_path}}/files/dhcpd.conf"
    - remote_peer_ip: "10.255.255.0"
    - remote_peer_prefix: "192.168.1.0"
    - remote_peer_netmask: "255.255.255.0"
  roles:
    - ipsec-client
    - router-host
    - docker-host
    - dhcp-server
    - unifi-controler
