---
- hosts: unifi0
  become: yes
  vars:
    - netplan_config: "{{role_path}}/files/09-intranet.yaml"
    - internet_iface: "enp4s0f0"
    # - intranet_iface: "enp4s0f1"
    - intranet_iface: "dummy0"
    - intranet_mask: "192.168.1.0/24"
    - server_address: "192.168.1.2"
    - server_conf: "{{role_path}}/files/dhcpd.conf"
    - docker_files: "/opt/docker/"
    - docker_volume: "/var/lib/docker/volumes"
  roles:
    - router-host
    - docker-host
    - dhcp-server
    - unifi-controler